/** Re-export shared contracts for app code. Prefer this or `@posnepal/shared` directly. */
export {
  OtpType,
  NetworkStatus,
  EntityStatus,
  SaleStatus,
  TicketStatus,
  UserRole,
  StaffRole,
  AdminRole,
  isOtpType,
  formatNpr,
  formatNumber,
  roundMoney,
  isEmail,
  isStrongPassword,
  scorePassword,
  getStockLevel,
  getStockLabel,
  sanitizePlainText,
  slugify,
  getInitials,
  formatDate,
  formatDateTime,
  formatRelativeTime,
  isExpired,
} from '@posnepal/shared';

export type {
  Id,
  AuthTokens,
  ApiErrorBody,
  Paginated,
  MoneyAmount,
  NetworkInfo,
  UserPublic,
  TenantPublic,
  ProductPublic,
} from '@posnepal/shared';
