export enum ENUM_ADMIN_STATUS_CODE_ERROR {
  ADMIN_NOT_FOUND_ERROR = 5200,
  ADMIN_ADMIN_NAME_EXISTS_ERROR = 5201,
  ADMIN_EMAIL_EXIST_ERROR = 5202,
  ADMIN_MOBILE_NUMBER_EXIST_ERROR = 5203,
  ADMIN_IS_ACTIVE_ERROR = 5204,
  ADMIN_INACTIVE_ERROR = 5205,
  ADMIN_INACTIVE_PERMANENT_ERROR = 5206,
  ADMIN_PASSWORD_NOT_MATCH_ERROR = 5207,
  ADMIN_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 5208,
  ADMIN_PASSWORD_EXPIRED_ERROR = 5209,
  ADMIN_PASSWORD_ATTEMPT_MAX_ERROR = 5210,
  ADMIN_BLOCKED_ERROR = 5211,
}
